import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({
  TestCLI.class
  TestConfiguration$1ConfigModifyThread.class
  TestConfiguration$Dingo.class
  TestConfiguration$Fake_ClassLoader.class
  TestConfiguration$JsonConfiguration.class
  TestConfiguration$JsonProperty.class
  TestConfiguration$Prop.class
  TestConfiguration$Yak.class
  TestConfiguration.class
  TestConfigurationDeprecation$1.class
  TestConfigurationDeprecation$2.class
  TestConfigurationDeprecation.class
  TestConfigurationFieldsBase.class
  TestConfigurationSubclass$1.class
  TestConfigurationSubclass$SubConf.class
  TestConfigurationSubclass.class
  TestConfServlet.class
  TestDeprecatedKeys.class
  TestGetInstances$AnotherClass.class
  TestGetInstances$ChildInterface.class
  TestGetInstances$SampleClass.class
  TestGetInstances$SampleInterface.class
  TestGetInstances.class
  TestReconfiguration$AsyncReconfigurableDummy.class
  TestReconfiguration$ReconfigurableDummy.class
  TestReconfiguration.class
  TestLoadBalancingKMSClientProvider.class
  TestCachingKeyProvider.class
  TestKeyProvider$MyKeyProvider.class
  TestKeyProvider.class
  TestKeyProviderCryptoExtension.class
  TestKeyProviderDelegationTokenExtension$MockKeyProvider.class
  TestKeyProviderDelegationTokenExtension.class
  TestKeyProviderFactory.class
  TestKeyShell.class
  TestValueQueue$1.class
  TestValueQueue$FillInfo.class
  TestValueQueue$MockFiller.class
  TestValueQueue.class
  TestOpensslSecureRandom.class
  TestOsSecureRandom.class
  TestCryptoCodec.class
  TestCryptoStreams$1.class
  TestCryptoStreams$FakeInputStream.class
  TestCryptoStreams$FakeOutputStream.class
  TestCryptoStreams.class
  TestCryptoStreamsForLocalFS.class
  TestCryptoStreamsNormal$1.class
  TestCryptoStreamsNormal.class
  TestCryptoStreamsWithOpensslAesCtrCryptoCodec.class
  TestOpensslCipher.class
  TestFTPContractCreate.class
  TestFTPContractDelete.class
  TestFTPContractMkdir.class
  TestFTPContractOpen.class
  TestFTPContractRename.class
  TestLocalFSContractAppend.class
  TestLocalFSContractCreate.class
  TestLocalFSContractDelete.class
  TestLocalFSContractLoaded.class
  TestLocalFSContractMkdir.class
  TestLocalFSContractOpen.class
  TestLocalFSContractRename.class
  TestLocalFSContractSeek.class
  TestRawlocalContractAppend.class
  TestRawlocalContractCreate.class
  TestRawlocalContractDelete.class
  TestRawlocalContractMkdir.class
  TestRawlocalContractOpen.class
  TestRawlocalContractRename.class
  TestRawlocalContractSeek.class
  TestRawLocalContractUnderlyingFileBehavior.class
  TestFTPFileSystem.class
  TestAcl.class
  TestFsPermission.class
  TestAnd.class
  TestFilterExpression$1.class
  TestFilterExpression.class
  TestFind$FileStatusChecker.class
  TestFind$TestExpression.class
  TestFind.class
  TestHelper.class
  TestIname.class
  TestName.class
  TestPrint.class
  TestPrint0.class
  TestResult.class
  TestAclCommands$StubFileSystem.class
  TestAclCommands.class
  TestCommandFactory$TestCommand1.class
  TestCommandFactory$TestCommand2.class
  TestCommandFactory$TestCommand3.class
  TestCommandFactory$TestRegistrar.class
  TestCommandFactory.class
  TestCopy$MockFileSystem.class
  TestCopy.class
  TestCopyPreserveFlag.class
  TestCount$MockContentSummary.class
  TestCount$MockFileSystem.class
  TestCount.class
  TestMove$1.class
  TestMove$InstrumentedRenameCommand.class
  TestMove$MockFileSystem.class
  TestMove.class
  TestPathData.class
  TestPathExceptions.class
  TestTextCommand$1.class
  TestTextCommand.class
  TestXAttrCommands.class
  TestAfsCheckPath$DummyFileSystem.class
  TestAfsCheckPath.class
  TestAvroFSInput.class
  TestBlockLocation.class
  TestChecksumFileSystem.class
  TestCommandFormat.class
  TestContentSummary.class
  TestDelegateToFileSystem.class
  TestDelegationTokenRenewer$1.class
  TestDelegationTokenRenewer$2.class
  TestDelegationTokenRenewer$3.class
  TestDelegationTokenRenewer$4.class
  TestDelegationTokenRenewer$RenewableFileSystem.class
  TestDelegationTokenRenewer.class
  TestDFVariations$XXDF.class
  TestDFVariations.class
  TestDU.class
  TestFcLocalFsPermission.class
  TestFcLocalFsUtil.class
  TestFileContext.class
  TestFileContextDeleteOnExit.class
  TestFileContextResolveAfs.class
  TestFileStatus.class
  TestFileSystemCaching$1.class
  TestFileSystemCaching$2.class
  TestFileSystemCaching$3.class
  TestFileSystemCaching$4.class
  TestFileSystemCaching$5.class
  TestFileSystemCaching$6.class
  TestFileSystemCaching$7.class
  TestFileSystemCaching$8.class
  TestFileSystemCaching$9.class
  TestFileSystemCaching$DefaultFs.class
  TestFileSystemCaching$InitializeForeverFileSystem.class
  TestFileSystemCaching.class
  TestFileSystemCanonicalization$DummyFileSystem.class
  TestFileSystemCanonicalization.class
  TestFileSystemInitialization.class
  TestFileSystemTokens$1.class
  TestFileSystemTokens.class
  TestFileUtil$MyFile.class
  TestFileUtil.class
  TestFilterFileSystem$DontCheck.class
  TestFilterFileSystem$FilterLocalFileSystem.class
  TestFilterFileSystem.class
  TestFilterFs$DontCheck.class
  TestFilterFs.class
  TestFSMainOperationsLocalFileSystem.class
  TestFsOptions.class
  TestFsShell.class
  TestFsShellCopy.class
  TestFsShellReturnCode$1.class
  TestFsShellReturnCode$2.class
  TestFsShellReturnCode$LocalFileSystemExtn.class
  TestFsShellReturnCode$RawLocalFileSystemExtn.class
  TestFsShellReturnCode.class
  TestGetFileBlockLocations$1.class
  TestGetFileBlockLocations.class
  TestGlobExpander.class
  TestGlobPattern.class
  TestHardLink$1win.class
  TestHardLink.class
  TestHarFileSystem$MustNotImplement.class
  TestHarFileSystem.class
  TestHarFileSystemBasics.class
  TestListFiles.class
  TestLocal_S3FileContextURI.class
  TestLocalDirAllocator.class
  TestLocalFileSystem$1.class
  TestLocalFileSystem.class
  TestLocalFileSystemPermission.class
  TestLocalFsFCStatistics.class
  TestLocalFSFileContextCreateMkdir.class
  TestLocalFSFileContextMainOperations.class
  TestPath.class
  TestS3_LocalFileContextURI.class
  TestStat$StatOutput.class
  TestStat.class
  TestSymlinkLocalFS.class
  TestSymlinkLocalFSFileContext.class
  TestSymlinkLocalFSFileSystem.class
  TestTrash$1.class
  TestTrash$TestLFS.class
  TestTrash$TestTrashPolicy.class
  TestTrash.class
  TestTruncatedInputBug.class
  TestChRootedFileSystem$MockFileSystem.class
  TestChRootedFileSystem.class
  TestChRootedFs.class
  TestFcCreateMkdirLocalFs.class
  TestFcMainOperationsLocalFs.class
  TestFcPermissionsLocalFs.class
  TestFSMainOperationsLocalFileSystem.class
  TestViewFileSystemDelegation$FakeFileSystem.class
  TestViewFileSystemDelegation.class
  TestViewFileSystemDelegationTokenSupport$FakeFileSystem.class
  TestViewFileSystemDelegationTokenSupport.class
  TestViewFileSystemLocalFileSystem.class
  TestViewFileSystemWithAuthorityLocalFileSystem.class
  TestViewFsConfig$1.class
  TestViewFsConfig$1Foo.class
  TestViewFsConfig.class
  TestViewfsFileStatus.class
  TestViewFsLocalFs.class
  TestViewFsTrash$TestLFS.class
  TestViewFsTrash.class
  TestViewFsURIs.class
  TestViewFsWithAuthorityLocalFs.class
  TestActiveStandbyElector$ActiveStandbyElectorTester.class
  TestActiveStandbyElector.class
  TestActiveStandbyElectorRealZK.class
  TestFailoverController.class
  TestHAAdmin$1.class
  TestHAAdmin.class
  TestHealthMonitor$1.class
  TestHealthMonitor$2.class
  TestHealthMonitor.class
  TestNodeFencer$AlwaysFailFencer.class
  TestNodeFencer$AlwaysSucceedFencer.class
  TestNodeFencer.class
  TestShellCommandFencer.class
  TestSshFenceByTcpPort.class
  TestZKFailoverController$1.class
  TestZKFailoverController.class
  TestZKFailoverControllerStress$RandomlyThrow.class
  TestZKFailoverControllerStress.class
  TestStaticUserWebFilter.class
  TestGlobalFilter$RecordingFilter$Initializer.class
  TestGlobalFilter$RecordingFilter.class
  TestGlobalFilter.class
  TestHtmlQuoting.class
  TestHttpCookieFlag$DummyAuthenticationFilter.class
  TestHttpCookieFlag$DummyFilterInitializer.class
  TestHttpCookieFlag.class
  TestHttpRequestLog.class
  TestHttpRequestLogAppender.class
  TestHttpServer$1.class
  TestHttpServer$DummyFilterInitializer.class
  TestHttpServer$DummyServletFilter$1.class
  TestHttpServer$DummyServletFilter.class
  TestHttpServer$EchoMapServlet.class
  TestHttpServer$EchoServlet.class
  TestHttpServer$HtmlContentServlet.class
  TestHttpServer$MyGroupsProvider.class
  TestHttpServer.class
  TestHttpServerLifecycle.class
  TestHttpServerWebapps.class
  TestPathFilter$RecordingFilter$Initializer.class
  TestPathFilter$RecordingFilter.class
  TestPathFilter.class
  TestServletFilter$ErrorFilter$Initializer.class
  TestServletFilter$ErrorFilter.class
  TestServletFilter$SimpleFilter$Initializer.class
  TestServletFilter$SimpleFilter.class
  TestServletFilter.class
  TestSSLHttpServer.class
  TestLz4CompressorDecompressor.class
  TestSnappyCompressorDecompressor$BytesGenerator.class
  TestSnappyCompressorDecompressor.class
  TestBlockDecompressorStream.class
  TestCodec.class
  TestCodecFactory$1.class
  TestCodecFactory$BarCodec.class
  TestCodecFactory$BaseCodec.class
  TestCodecFactory$FooBarCodec.class
  TestCodecFactory$FooCodec.class
  TestCodecFactory$NewGzipCodec.class
  TestCodecFactory.class
  TestCodecPool$1.class
  TestCodecPool$2.class
  TestCodecPool$3.class
  TestCodecPool$4.class
  TestCodecPool.class
  TestCompressorDecompressor.class
  TestCompressorStream.class
  TestZlibCompressorDecompressor.class
  TestTFile.class
  TestTFileByteArrays.class
  TestTFileComparator2.class
  TestTFileComparators.class
  TestTFileJClassComparatorByteArrays.class
  TestTFileLzoCodecsByteArrays.class
  TestTFileLzoCodecsStreams.class
  TestTFileNoneCodecsByteArrays.class
  TestTFileNoneCodecsJClassComparatorByteArrays.class
  TestTFileNoneCodecsStreams.class
  TestTFileSeek$IntegerRange.class
  TestTFileSeek$MyOptions.class
  TestTFileSeek.class
  TestTFileSeqFileComparison$KVAppendable.class
  TestTFileSeqFileComparison$KVReadable.class
  TestTFileSeqFileComparison$MyOptions.class
  TestTFileSeqFileComparison$SeqFileAppendable.class
  TestTFileSeqFileComparison$SeqFileReadable.class
  TestTFileSeqFileComparison$TFileAppendable.class
  TestTFileSeqFileComparison$TFileReadable.class
  TestTFileSeqFileComparison.class
  TestTFileSplit.class
  TestTFileStreams.class
  TestTFileUnsortedByteArrays.class
  TestVLong.class
  TestNativeIO$1.class
  TestNativeIO.class
  TestSharedFileDescriptorFactory.class
  TestDefaultRetryPolicy.class
  TestFailoverProxy$1.class
  TestFailoverProxy$ConcurrentMethodThread.class
  TestFailoverProxy$FailOverOnceOnAnyExceptionPolicy.class
  TestFailoverProxy$FlipFlopProxyProvider.class
  TestFailoverProxy$SynchronizedUnreliableImplementation.class
  TestFailoverProxy.class
  TestRetryProxy$1.class
  TestRetryProxy$2.class
  TestRetryProxy.class
  TestAvroSerialization$InnerRecord.class
  TestAvroSerialization$RefSerializable.class
  TestAvroSerialization.class
  TestSerializationFactory.class
  TestWritableSerialization$TestWC.class
  TestWritableSerialization.class
  TestArrayFile$1.class
  TestArrayFile.class
  TestArrayPrimitiveWritable.class
  TestArrayWritable$TextArrayWritable.class
  TestArrayWritable.class
  TestBloomMapFile$1.class
  TestBloomMapFile$2.class
  TestBloomMapFile.class
  TestBooleanWritable.class
  TestBoundedByteArrayOutputStream$ResettableBoundedByteArrayOutputStream.class
  TestBoundedByteArrayOutputStream.class
  TestBytesWritable.class
  TestDataByteBuffers.class
  TestDefaultStringifier.class
  TestEnumSetWritable$TestEnumSet.class
  TestEnumSetWritable.class
  TestGenericWritable$Bar.class
  TestGenericWritable$Baz.class
  TestGenericWritable$Foo.class
  TestGenericWritable$FooGenericWritable.class
  TestGenericWritable.class
  TestIOUtils$NoEntry3Filter.class
  TestIOUtils.class
  TestMapFile$1.class
  TestMapFile$2.class
  TestMapFile.class
  TestMapWritable.class
  TestMD5Hash$1.class
  TestMD5Hash$2.class
  TestMD5Hash$3.class
  TestMD5Hash.class
  TestObjectWritableProtos.class
  TestSecureIOUtils.class
  TestSequenceFile$1.class
  TestSequenceFile$TestFSDataInputStream.class
  TestSequenceFile.class
  TestSequenceFileAppend.class
  TestSequenceFileSerialization.class
  TestSequenceFileSync.class
  TestSetFile.class
  TestSortedMapWritable.class
  TestText$ConcurrentEncodeDecodeThread.class
  TestText.class
  TestTextNonUTF8.class
  TestUTF8.class
  TestVersionedWritable$AdvancedVersionedWritable.class
  TestVersionedWritable$SimpleVersionedWritable.class
  TestVersionedWritable$SimpleVersionedWritableV2.class
  TestVersionedWritable.class
  TestWritable$Frob.class
  TestWritable$FrobComparator.class
  TestWritable$SimpleWritable.class
  TestWritable$SimpleWritableComparable.class
  TestWritable.class
  TestWritableName$SimpleWritable.class
  TestWritableName.class
  TestWritableUtils.class
  TestProtos$1.class
  TestProtos$EchoRequestProto$1.class
  TestProtos$EchoRequestProto$Builder.class
  TestProtos$EchoRequestProto.class
  TestProtos$EchoRequestProtoOrBuilder.class
  TestProtos$EchoResponseProto$1.class
  TestProtos$EchoResponseProto$Builder.class
  TestProtos$EchoResponseProto.class
  TestProtos$EchoResponseProtoOrBuilder.class
  TestProtos$EmptyRequestProto$1.class
  TestProtos$EmptyRequestProto$Builder.class
  TestProtos$EmptyRequestProto.class
  TestProtos$EmptyRequestProtoOrBuilder.class
  TestProtos$EmptyResponseProto$1.class
  TestProtos$EmptyResponseProto$Builder.class
  TestProtos$EmptyResponseProto.class
  TestProtos$EmptyResponseProtoOrBuilder.class
  TestProtos.class
  TestRpcServiceProtos$1.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$1.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$2.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$BlockingInterface.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$BlockingStub.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$Interface.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$Stub.class
  TestRpcServiceProtos$TestProtobufRpc2Proto.class
  TestRpcServiceProtos$TestProtobufRpcProto$1.class
  TestRpcServiceProtos$TestProtobufRpcProto$2.class
  TestRpcServiceProtos$TestProtobufRpcProto$BlockingInterface.class
  TestRpcServiceProtos$TestProtobufRpcProto$BlockingStub.class
  TestRpcServiceProtos$TestProtobufRpcProto$Interface.class
  TestRpcServiceProtos$TestProtobufRpcProto$Stub.class
  TestRpcServiceProtos$TestProtobufRpcProto.class
  TestRpcServiceProtos.class
  TestCallQueueManager$FakeCall.class
  TestCallQueueManager$Putter.class
  TestCallQueueManager$Taker.class
  TestCallQueueManager.class
  TestDecayRpcScheduler.class
  TestFairCallQueue$Putter.class
  TestFairCallQueue$Taker.class
  TestFairCallQueue.class
  TestIdentityProviders$FakeSchedulable.class
  TestIdentityProviders.class
  TestIPC$1.class
  TestIPC$10.class
  TestIPC$11.class
  TestIPC$12.class
  TestIPC$2.class
  TestIPC$3.class
  TestIPC$4.class
  TestIPC$5.class
  TestIPC$6.class
  TestIPC$7.class
  TestIPC$8.class
  TestIPC$9.class
  TestIPC$CallInfo.class
  TestIPC$DummyProtocol.class
  TestIPC$IOEOnReadWritable.class
  TestIPC$IOEOnWriteWritable.class
  TestIPC$NetworkTraces.class
  TestIPC$RTEOnReadWritable.class
  TestIPC$RTEOnWriteWritable.class
  TestIPC$SerialCaller.class
  TestIPC$TestInvocationHandler.class
  TestIPC$TestServer.class
  TestIPC$TestServerQueue.class
  TestIPC.class
  TestIPCServerResponder$Caller.class
  TestIPCServerResponder$TestServer.class
  TestIPCServerResponder.class
  TestMiniRPCBenchmark.class
  TestMultipleProtocolServer$Bar.class
  TestMultipleProtocolServer$BarImpl.class
  TestMultipleProtocolServer$Foo0.class
  TestMultipleProtocolServer$Foo0Impl.class
  TestMultipleProtocolServer$Foo1.class
  TestMultipleProtocolServer$Foo1Impl.class
  TestMultipleProtocolServer$FooUnimplemented.class
  TestMultipleProtocolServer$Mixin.class
  TestMultipleProtocolServer.class
  TestProtoBufRpc$PBServer2Impl.class
  TestProtoBufRpc$PBServerImpl.class
  TestProtoBufRpc$TestRpcService.class
  TestProtoBufRpc$TestRpcService2.class
  TestProtoBufRpc.class
  TestRetryCache$1.class
  TestRetryCache$TestServer.class
  TestRetryCache.class
  TestRetryCacheMetrics.class
  TestRPC$1.class
  TestRPC$2.class
  TestRPC$SlowRPC.class
  TestRPC$StoppedInvocationHandler.class
  TestRPC$StoppedProtocol.class
  TestRPC$StoppedRpcEngine.class
  TestRPC$TestImpl.class
  TestRPC$TestPolicyProvider.class
  TestRPC$TestProtocol.class
  TestRPC$Transactions.class
  TestRPC.class
  TestRPCCallBenchmark.class
  TestRPCCompatibility$1.class
  TestRPCCompatibility$TestImpl0.class
  TestRPCCompatibility$TestImpl1.class
  TestRPCCompatibility$TestImpl2.class
  TestRPCCompatibility$TestProtocol0.class
  TestRPCCompatibility$TestProtocol1.class
  TestRPCCompatibility$TestProtocol2.class
  TestRPCCompatibility$TestProtocol3.class
  TestRPCCompatibility$TestProtocol4.class
  TestRPCCompatibility$Version2Client.class
  TestRPCCompatibility.class
  TestRPCWaitForProxy$1.class
  TestRPCWaitForProxy$RpcThread.class
  TestRPCWaitForProxy.class
  TestSaslRPC$1.class
  TestSaslRPC$2.class
  TestSaslRPC$3.class
  TestSaslRPC$AuthSaslPropertiesResolver.class
  TestSaslRPC$BadTokenSecretManager.class
  TestSaslRPC$CustomSecurityInfo$1.class
  TestSaslRPC$CustomSecurityInfo$2.class
  TestSaslRPC$CustomSecurityInfo.class
  TestSaslRPC$TestPlainCallbacks$Client.class
  TestSaslRPC$TestPlainCallbacks$Server.class
  TestSaslRPC$TestPlainCallbacks.class
  TestSaslRPC$TestSaslImpl.class
  TestSaslRPC$TestSaslProtocol.class
  TestSaslRPC$TestTokenIdentifier.class
  TestSaslRPC$TestTokenSecretManager.class
  TestSaslRPC$TestTokenSelector.class
  TestSaslRPC$UseToken.class
  TestSaslRPC.class
  TestServer.class
  TestSocketFactory$DummySocketFactory.class
  TestSocketFactory.class
  TestWeightedRoundRobinMultiplexer.class
  TestJMXJsonServlet.class
  TestLog4Json$1.class
  TestLog4Json$TestLogger.class
  TestLog4Json$TestLoggerRepository.class
  TestLog4Json.class
  TestLogLevel.class
  TestGangliaContext.class
  TestOutputRecord.class
  TestMetricsServlet.class
  TestPatternFilter.class
  TestGangliaMetrics$MockDatagramSocket.class
  TestGangliaMetrics$TestSource.class
  TestGangliaMetrics.class
  TestGraphiteMetrics.class
  TestMetricsCollectorImpl.class
  TestMetricsConfig.class
  TestMetricsSourceAdapter$PurgableSource.class
  TestMetricsSourceAdapter$TestSource.class
  TestMetricsSourceAdapter.class
  TestMetricsSystemImpl$1.class
  TestMetricsSystemImpl$2.class
  TestMetricsSystemImpl$3.class
  TestMetricsSystemImpl$4.class
  TestMetricsSystemImpl$CollectingSink.class
  TestMetricsSystemImpl$HangingSink.class
  TestMetricsSystemImpl$TestClosableSink.class
  TestMetricsSystemImpl$TestSink.class
  TestMetricsSystemImpl$TestSource.class
  TestMetricsSystemImpl$TestSource2.class
  TestMetricsSystemImpl.class
  TestMetricsVisitor.class
  TestSinkQueue$1.class
  TestSinkQueue$10$1.class
  TestSinkQueue$10.class
  TestSinkQueue$2$1.class
  TestSinkQueue$2.class
  TestSinkQueue$3.class
  TestSinkQueue$4.class
  TestSinkQueue$5.class
  TestSinkQueue$6.class
  TestSinkQueue$7.class
  TestSinkQueue$8.class
  TestSinkQueue$9.class
  TestSinkQueue$Fun.class
  TestSinkQueue.class
  TestInterns.class
  TestMetricsAnnotations$BadHybridMetrics.class
  TestMetricsAnnotations$BadMetrics.class
  TestMetricsAnnotations$BadMetrics2.class
  TestMetricsAnnotations$BadMetrics3.class
  TestMetricsAnnotations$EmptyMetrics.class
  TestMetricsAnnotations$HybridMetrics.class
  TestMetricsAnnotations$MyMetrics.class
  TestMetricsAnnotations$MyMetrics2.class
  TestMetricsAnnotations$MyMetrics3.class
  TestMetricsAnnotations.class
  TestMetricsRegistry$1.class
  TestMetricsRegistry$2.class
  TestMetricsRegistry$3.class
  TestMetricsRegistry$4.class
  TestMetricsRegistry$5.class
  TestMetricsRegistry$6.class
  TestMetricsRegistry$7.class
  TestMetricsRegistry$8.class
  TestMetricsRegistry.class
  TestMutableMetrics$TestProtocol.class
  TestMutableMetrics.class
  TestUniqNames.class
  TestGangliaSink.class
  TestFileSink$MyMetrics1.class
  TestFileSink$MyMetrics2.class
  TestFileSink.class
  TestJvmMetrics.class
  TestMetricsCache.class
  TestSampleQuantiles.class
  TestSampleStat.class
  TestClusterTopology$NodeElement.class
  TestClusterTopology.class
  TestDNS.class
  TestNetUtils.class
  TestNetworkTopologyWithNodeGroup.class
  TestScriptBasedMapping.class
  TestScriptBasedMappingWithDependency.class
  TestSocketIOWithTimeout$1.class
  TestSocketIOWithTimeout.class
  TestStaticMapping.class
  TestSwitchMapping$1.class
  TestSwitchMapping$StandaloneSwitchMapping.class
  TestSwitchMapping.class
  TestTableMapping.class
  TestDomainSocket$1.class
  TestDomainSocket$2.class
  TestDomainSocket$3.class
  TestDomainSocket$4.class
  TestDomainSocket$5.class
  TestDomainSocket$6.class
  TestDomainSocket$7.class
  TestDomainSocket$8.class
  TestDomainSocket$9.class
  TestDomainSocket$ArrayBackedByteBufferReadStrategy.class
  TestDomainSocket$DirectByteBufferReadStrategy.class
  TestDomainSocket$InputStreamReadStrategy.class
  TestDomainSocket$OutputStreamWriteStrategy.class
  TestDomainSocket$PassedFile.class
  TestDomainSocket$ReadStrategy.class
  TestDomainSocket$Success.class
  TestDomainSocket$WriteStrategy.class
  TestDomainSocket.class
  TestDomainSocketWatcher$1.class
  TestDomainSocketWatcher$2.class
  TestDomainSocketWatcher$3$1.class
  TestDomainSocketWatcher$3.class
  TestDomainSocketWatcher$4.class
  TestDomainSocketWatcher$5.class
  TestDomainSocketWatcher.class
  TestCredentialProvider.class
  TestCredentialProviderFactory.class
  TestCredShell$MockPasswordReader.class
  TestCredShell.class
  TestAccessControlList.class
  TestProxyServers.class
  TestProxyUsers$TestDummyImpersonationProvider.class
  TestProxyUsers.class
  TestServiceAuthorization$1.class
  TestServiceAuthorization$TestPolicyProvider.class
  TestServiceAuthorization$TestProtocol1.class
  TestServiceAuthorization.class
  TestCrossOriginFilter$FilterConfigTest.class
  TestCrossOriginFilter.class
  TestReloadingX509TrustManager.class
  TestSSLFactory.class
  TestAuthenticationFilter$1.class
  TestAuthenticationFilter.class
  TestCompositeGroupMapping$1.class
  TestCompositeGroupMapping$ClusterProvider.class
  TestCompositeGroupMapping$GroupMappingProviderBase.class
  TestCompositeGroupMapping$TestUser.class
  TestCompositeGroupMapping$UserProvider.class
  TestCompositeGroupMapping.class
  TestCredentials.class
  TestDoAsEffectiveUser$1.class
  TestDoAsEffectiveUser$2.class
  TestDoAsEffectiveUser$3.class
  TestDoAsEffectiveUser$4.class
  TestDoAsEffectiveUser$5.class
  TestDoAsEffectiveUser$6.class
  TestDoAsEffectiveUser$7.class
  TestDoAsEffectiveUser$8.class
  TestDoAsEffectiveUser$TestImpl.class
  TestDoAsEffectiveUser$TestProtocol.class
  TestDoAsEffectiveUser.class
  TestGroupFallback.class
  TestGroupsCaching$1.class
  TestGroupsCaching$2.class
  TestGroupsCaching$ExceptionalGroupMapping.class
  TestGroupsCaching$FakeGroupMapping.class
  TestGroupsCaching$FakeunPrivilegedGroupMapping.class
  TestGroupsCaching.class
  TestHttpCrossOriginFilterInitializer.class
  TestJNIGroupsMapping.class
  TestLdapGroupsMapping.class
  TestNetgroupCache.class
  TestProxyUserFromEnv.class
  TestSecurityUtil.class
  TestShellBasedIdMapping.class
  TestUGILoginFromKeytab.class
  TestUGIWithExternalKdc.class
  TestUserFromEnv.class
  TestUserGroupInformation$1.class
  TestUserGroupInformation$2.class
  TestUserGroupInformation$3.class
  TestUserGroupInformation$4.class
  TestUserGroupInformation$5.class
  TestUserGroupInformation$6.class
  TestUserGroupInformation$7.class
  TestUserGroupInformation$8.class
  TestUserGroupInformation$DummyLoginConfiguration.class
  TestUserGroupInformation$GetTokenThread.class
  TestUserGroupInformation.class
  TestWhitelistBasedResolver.class
  TestDelegationToken$1.class
  TestDelegationToken$1tokenIssuerThread.class
  TestDelegationToken$2.class
  TestDelegationToken$3.class
  TestDelegationToken$4.class
  TestDelegationToken$TestDelegationTokenIdentifier.class
  TestDelegationToken$TestDelegationTokenSecretManager.class
  TestDelegationToken$TokenSelector.class
  TestDelegationToken.class
  TestZKDelegationTokenSecretManager$1.class
  TestZKDelegationTokenSecretManager$2.class
  TestZKDelegationTokenSecretManager.class
  TestDelegationTokenAuthenticationHandlerWithMocks$MockDelegationTokenAuthenticationHandler$1.class
  TestDelegationTokenAuthenticationHandlerWithMocks$MockDelegationTokenAuthenticationHandler.class
  TestDelegationTokenAuthenticationHandlerWithMocks.class
  TestDelegationTokenManager.class
  TestWebDelegationToken$1.class
  TestWebDelegationToken$2.class
  TestWebDelegationToken$3.class
  TestWebDelegationToken$4.class
  TestWebDelegationToken$5.class
  TestWebDelegationToken$6.class
  TestWebDelegationToken$7.class
  TestWebDelegationToken$AFilter.class
  TestWebDelegationToken$DummyAuthenticationHandler.class
  TestWebDelegationToken$DummyDelegationTokenAuthenticationHandler.class
  TestWebDelegationToken$DummyDelegationTokenSecretManager.class
  TestWebDelegationToken$KDTAFilter.class
  TestWebDelegationToken$KerberosConfiguration.class
  TestWebDelegationToken$NoDTFilter.class
  TestWebDelegationToken$NoDTHandlerDTAFilter.class
  TestWebDelegationToken$PingServlet.class
  TestWebDelegationToken$PseudoDTAFilter.class
  TestWebDelegationToken$UGIServlet.class
  TestWebDelegationToken$UserServlet.class
  TestWebDelegationToken.class
  TestToken.class
  TestCompositeService$1$1.class
  TestCompositeService$1.class
  TestCompositeService$2$1.class
  TestCompositeService$2$2.class
  TestCompositeService$2$3.class
  TestCompositeService$2.class
  TestCompositeService$AddSiblingService.class
  TestCompositeService$CompositeServiceAddingAChild.class
  TestCompositeService$CompositeServiceImpl.class
  TestCompositeService$ServiceManager.class
  TestCompositeService$ServiceTestRuntimeException.class
  TestCompositeService.class
  TestGlobalStateChangeListener.class
  TestServiceLifecycle$1.class
  TestServiceLifecycle$AsyncSelfTerminatingService.class
  TestServiceLifecycle$NotifyingListener.class
  TestServiceLifecycle$SelfTerminatingService.class
  TestServiceLifecycle$SelfUnregisteringBreakableStateChangeListener.class
  TestServiceLifecycle$StartInInitService.class
  TestServiceLifecycle$StopInInitService.class
  TestServiceLifecycle.class
  TestJUnitSetup.class
  TestMultithreadedTestUtil$1.class
  TestMultithreadedTestUtil$2.class
  TestMultithreadedTestUtil$3.class
  TestMultithreadedTestUtil$4.class
  TestMultithreadedTestUtil.class
  TestTimedOutTestsListener$Deadlock$DeadlockThread.class
  TestTimedOutTestsListener$Deadlock$Monitor.class
  TestTimedOutTestsListener$Deadlock.class
  TestTimedOutTestsListener.class
  TestTraceUtils.class
  TestBloomFilters$1.class
  TestBloomFilters$2.class
  TestBloomFilters$Digits.class
  TestBloomFilters.class
  TestChildReaper.class
  TestHash.class
  TestApplicationClassLoader.class
  TestAsyncDiskService$ExampleTask.class
  TestAsyncDiskService.class
  TestCacheableIPList.class
  TestChunkedArrayList.class
  TestClasspath.class
  TestClassUtil.class
  TestDataChecksum$Harness.class
  TestDataChecksum.class
  TestDirectBufferPool.class
  TestDiskChecker.class
  TestFileBasedIPList.class
  TestGenericOptionsParser.class
  TestGenericsUtil$1.class
  TestGenericsUtil$GenericClass.class
  TestGenericsUtil.class
  TestGSet$GSetTestCase.class
  TestGSet$IntData.class
  TestGSet$IntElement.class
  TestGSet.class
  TestHostsFileReader.class
  TestHttpExceptionUtils.class
  TestIdentityHashStore$1.class
  TestIdentityHashStore$2.class
  TestIdentityHashStore$3.class
  TestIdentityHashStore$4.class
  TestIdentityHashStore$5.class
  TestIdentityHashStore$6.class
  TestIdentityHashStore$Key.class
  TestIdentityHashStore.class
  TestIndexedSort$MeasuredSortable.class
  TestIndexedSort$SampleSortable.class
  TestIndexedSort$WritableSortable.class
  TestIndexedSort.class
  TestJarFinder.class
  TestLightWeightCache$IntData.class
  TestLightWeightCache$IntEntry.class
  TestLightWeightCache$LightWeightCacheTestCase$1.class
  TestLightWeightCache$LightWeightCacheTestCase.class
  TestLightWeightCache.class
  TestLightWeightGSet$TestElement.class
  TestLightWeightGSet.class
  TestLineReader.class
  TestMachineList.class
  TestNativeCodeLoader.class
  TestNativeCrc32.class
  TestNativeLibraryChecker.class
  TestOptions.class
  TestProgress.class
  TestProtoUtil.class
  TestPureJavaCrc32$PerformanceTest$1.class
  TestPureJavaCrc32$PerformanceTest$BenchResult.class
  TestPureJavaCrc32$PerformanceTest.class
  TestPureJavaCrc32$Table.class
  TestPureJavaCrc32.class
  TestReflectionUtils$1.class
  TestReflectionUtils$2.class
  TestReflectionUtils$LoadedInChild.class
  TestReflectionUtils$NoDefaultCtor.class
  TestReflectionUtils$Parent.class
  TestReflectionUtils.class
  TestRunJar.class
  TestShell$1.class
  TestShell$Command.class
  TestShell.class
  TestShutdownHookManager$1.class
  TestShutdownHookManager$2.class
  TestShutdownHookManager.class
  TestShutdownThreadsHelper$1.class
  TestShutdownThreadsHelper.class
  TestSignalLogger.class
  TestStopWatch.class
  TestStringInterner.class
  TestStringUtils.class
  TestVersionUtil.class
  TestWinUtils.class
  TestZKUtil.class
})
public class AllTests { /* empty */}
