import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({
  TestCommandShell$Example.class
  TestCommandShell.class
  TestCommandShell$Example$Hello.class
  TestCommandShell$Example$Goodbye.class
  TestMultithreadedTestUtil$4.class
  TestGenericTestUtils$1.class
  TestLambdaTestUtils$2.class
  TestMultithreadedTestUtil$3.class
  TestLambdaTestUtils.class
  TestMultithreadedTestUtil$2.class
  TestLambdaTestUtils$4.class
  TestJUnitSetup.class
  TestGenericTestUtils.class
  TestTimedOutTestsListener$Deadlock$Monitor.class
  TestMultithreadedTestUtil$1.class
  TestLambdaTestUtils$3.class
  TestTimedOutTestsListener$Deadlock$DeadlockThread.class
  TestLambdaTestUtils$1.class
  TestMultithreadedTestUtil.class
  TestLambdaTestUtils$6$1.class
  TestTimedOutTestsListener.class
  TestGenericTestUtils$BrokenException.class
  TestTimedOutTestsListener$Deadlock.class
  TestLambdaTestUtils$5.class
  TestLambdaTestUtils$6.class
  TestBooleanWritable.class
  TestBoundedByteArrayOutputStream$ResettableBoundedByteArrayOutputStream.class
  TestSecureIOUtils.class
  TestIOUtils$NoEntry3Filter.class
  TestCodecFactory$BaseCodec.class
  TestBlockDecompressorStream.class
  TestCodecPool$2.class
  TestCodecFactory$FooCodec.class
  TestSnappyCompressorDecompressor$1.class
  TestSnappyCompressorDecompressor$BytesGenerator.class
  TestSnappyCompressorDecompressor.class
  TestCodecPool$4.class
  TestCompressorDecompressor.class
  TestCompressorStream.class
  TestBzip2CompressorDecompressor.class
  TestBzip2CompressorDecompressor$1.class
  TestCodecFactory$BarCodec.class
  TestCodec.class
  TestCodecPool$1.class
  TestCodecPool.class
  TestZlibCompressorDecompressor.class
  TestZlibCompressorDecompressor$1.class
  TestCompressionStreamReuse.class
  TestCodecPool$3.class
  TestCodecFactory$NewGzipCodec.class
  TestLz4CompressorDecompressor$1.class
  TestLz4CompressorDecompressor.class
  TestCodecFactory.class
  TestCodecFactory$FooBarCodec.class
  TestDecompressorStream.class
  TestZStandardCompressorDecompressor.class
  TestZStandardCompressorDecompressor$1.class
  TestCodecFactory$1.class
  TestMapWritable.class
  TestArrayWritable.class
  TestDefaultStringifier.class
  TestWritable$SimpleWritable.class
  TestSequenceFile$TestFSDataInputStream.class
  TestIOUtils.class
  TestText.class
  TestBytesWritable.class
  TestTFileLzoCodecsStreams.class
  TestTFileUnsortedByteArrays.class
  TestTFileComparators.class
  TestTFileNoneCodecsStreams.class
  TestTFileComparator2.class
  TestTFileNoneCodecsByteArrays.class
  TestTFileSeqFileComparison$SeqFileReadable.class
  TestTFileSeek$MyOptions.class
  TestTFileSplit.class
  TestTFileSeek$IntegerRange.class
  TestTFileSeqFileComparison.class
  TestTFileStreams.class
  TestTFileSeek.class
  TestTFileNoneCodecsJClassComparatorByteArrays.class
  TestTFile.class
  TestTFileSeqFileComparison$SeqFileAppendable.class
  TestTFileSeqFileComparison$TFileAppendable.class
  TestVLong.class
  TestCompression.class
  TestTFileSeqFileComparison$KVReadable.class
  TestTFileByteArrays.class
  TestTFileJClassComparatorByteArrays.class
  TestTFileLzoCodecsByteArrays.class
  TestTFileSeqFileComparison$TFileReadable.class
  TestTFileSeqFileComparison$MyOptions.class
  TestTFileSeqFileComparison$KVAppendable.class
  TestNativeIO.class
  TestSharedFileDescriptorFactory.class
  TestNativeIO$1.class
  TestDataByteBuffers.class
  TestArrayFile$1.class
  TestSerializationFactory.class
  TestAvroSerialization.class
  TestAvroSerialization$InnerRecord.class
  TestAvroSerialization$RefSerializable.class
  TestWritableSerialization.class
  TestWritableSerialization$TestWC.class
  TestEnumSetWritable.class
  TestText$ConcurrentEncodeDecodeThread.class
  TestSortedMapWritable.class
  TestEnumSetWritable$TestEnumSet.class
  TestRetryProxy$1.class
  TestRetryProxy$3.class
  TestFailoverProxy$SynchronizedUnreliableImplementation.class
  TestConnectionRetryPolicy.class
  TestRetryProxy.class
  TestFailoverProxy.class
  TestFailoverProxy$1.class
  TestDefaultRetryPolicy.class
  TestRetryProxy$2.class
  TestFailoverProxy$ConcurrentMethodThread.class
  TestFailoverProxy$FlipFlopProxyProvider.class
  TestFailoverProxy$FailOverOnceOnAnyExceptionPolicy.class
  TestGenericWritable$Foo.class
  TestMD5Hash$1.class
  TestUTF8.class
  TestWritable.class
  TestVersionedWritable$SimpleVersionedWritable.class
  TestSetFile.class
  TestSequenceFile.class
  TestMapFile.class
  TestMD5Hash$3.class
  TestWritableName.class
  TestGenericWritable$Bar.class
  TestVersionedWritable.class
  TestTextNonUTF8.class
  TestMD5Hash.class
  TestMD5Hash$2.class
  TestArrayWritable$TextArrayWritable.class
  TestWritable$FrobComparator.class
  TestWritable$SimpleWritableComparable.class
  TestBloomMapFile$1.class
  TestSequenceFileSync.class
  TestArrayPrimitiveWritable.class
  TestGenericWritable.class
  TestVersionedWritable$AdvancedVersionedWritable.class
  TestMapFile$2.class
  TestBoundedByteArrayOutputStream.class
  TestBloomMapFile$2.class
  TestVersionedWritable$SimpleVersionedWritableV2.class
  TestSequenceFileSerialization.class
  TestGenericWritable$FooGenericWritable.class
  TestHHErasureCoderBase.class
  TestErasureCoderBase.class
  TestHHXORErasureCoder.class
  TestErasureCoderBase$TestBlock.class
  TestRSErasureCoder.class
  TestXORCoder.class
  TestCoderBase.class
  TestCoderUtil.class
  TestRSRawCoderInteroperable1.class
  TestXORRawCoder.class
  TestXORRawCoderInteroperable2.class
  TestRSRawCoderBase.class
  TestXORRawCoderBase.class
  TestRawErasureCoderBenchmark.class
  TestRSLegacyRawCoder.class
  TestRSRawCoderInteroperable2.class
  TestXORRawCoderInteroperable1.class
  TestNativeRSRawCoder.class
  TestNativeXORRawCoder.class
  TestRawCoderBase.class
  TestRSRawCoder.class
  TestDummyRawCoder.class
  TestHHXORErasureCodec.class
  TestCodecRawCoderMapping.class
  TestCodecRegistry$1RSUserDefinedIncorrectFactory.class
  TestCodecRegistry.class
  TestECSchema.class
  TestObjectWritableProtos.class
  TestMapFile$1.class
  TestSequenceFileAppend.class
  TestWritableName$SimpleWritable.class
  TestWritableUtils.class
  TestWritable$Frob.class
  TestBloomMapFile.class
  TestArrayFile.class
  TestGenericWritable$Baz.class
  TestSequenceFile$1.class
  TestFileSink.class
  TestFileSink$MyMetrics2.class
  TestGangliaSink.class
  TestRollingFileSystemSink.class
  TestFileSink$MyMetrics1.class
  TestRollingFileSystemSinkWithLocal.class
  TestMetricsSourceAdapter$SourceReader.class
  TestMetricsSystemImpl$TestSource.class
  TestSinkQueue$Fun.class
  TestMetricsSourceAdapter$1.class
  TestGangliaMetrics$MockDatagramSocket.class
  TestMetricsSystemImpl$TestClosableSink.class
  TestSinkQueue$4.class
  TestMetricsSystemImpl$HangingSink.class
  TestMetricsSystemImpl$2.class
  TestMetricsSystemImpl$CollectingSink.class
  TestGangliaMetrics.class
  TestSinkQueue$1.class
  TestMetricsSourceAdapter.class
  TestMetricsSourceAdapter$TestSource.class
  TestStatsDMetrics.class
  TestSinkQueue.class
  TestSinkQueue$8.class
  TestGangliaMetrics$TestSource.class
  TestMetricsSystemImpl$1.class
  TestMetricsSystemImpl$TestSource2.class
  TestGraphiteMetrics.class
  TestSinkQueue$10.class
  TestMetricsConfig.class
  TestSinkQueue$7.class
  TestMetricsVisitor.class
  TestSinkQueue$2.class
  TestMetricsSourceAdapter$PurgableSource.class
  TestSinkQueue$6.class
  TestMetricsCollectorImpl.class
  TestSinkQueue$5.class
  TestMetricsSystemImpl$TestSink.class
  TestSinkQueue$3.class
  TestMetricsSourceAdapter$TestMetricsSource.class
  TestMetricsSystemImpl$3.class
  TestMetricsSystemImpl$4.class
  TestSinkQueue$2$1.class
  TestMetricsSourceAdapter$SourceUpdater.class
  TestSinkQueue$10$1.class
  TestMetricsSystemImpl.class
  TestSinkQueue$9.class
  TestPatternFilter.class
  TestJvmMetrics.class
  TestMetricsCache.class
  TestSampleStat.class
  TestSampleQuantiles.class
  TestMetricsAnnotations$BadMetrics.class
  TestMutableMetrics$TestProtocol.class
  TestMutableRollingAverages$DummyTestMetric.class
  TestMetricsAnnotations$BadMetrics3.class
  TestMetricsRegistry$2.class
  TestMetricsRegistry$8.class
  TestMutableRollingAverages.class
  TestMetricsRegistry$1.class
  TestMetricsAnnotations$EmptyMetrics.class
  TestMetricsAnnotations$MyMetrics2.class
  TestMetricsAnnotations$MyMetrics.class
  TestMetricsRegistry$9.class
  TestMutableRollingAverages$1.class
  TestMutableMetrics.class
  TestMetricsAnnotations$HybridMetrics.class
  TestInterns.class
  TestMetricsRegistry$5.class
  TestMetricsRegistry$4.class
  TestMetricsRegistry$3.class
  TestUniqNames.class
  TestMetricsAnnotations$MyMetrics3.class
  TestMetricsRegistry.class
  TestMetricsRegistry$6.class
  TestMetricsAnnotations.class
  TestMetricsAnnotations$BadHybridMetrics.class
  TestMetricsRegistry$7.class
  TestMutableMetrics$1.class
  TestMetricsAnnotations$BadMetrics2.class
  TestHttpCookieFlag$DummyFilterInitializer.class
  TestHttpServerWebapps.class
  TestGlobalFilter.class
  TestAuthenticationSessionCookie.class
  TestHttpServerLifecycle.class
  TestHttpServer.class
  TestAuthenticationSessionCookie$Dummy2AuthenticationFilter.class
  TestPathFilter$RecordingFilter$Initializer.class
  TestHtmlQuoting.class
  TestSSLHttpServer$PrefferedCipherSSLSocketFactory.class
  TestHttpCookieFlag.class
  TestHttpRequestLogAppender.class
  TestServletFilter$SimpleFilter.class
  TestSSLHttpServer.class
  TestGlobalFilter$RecordingFilter.class
  TestServletFilter$ErrorFilter$Initializer.class
  TestHttpServer$DummyServletFilter$1.class
  TestServletFilter.class
  TestHttpServer$HtmlContentServlet.class
  TestServletFilter$SimpleFilter$Initializer.class
  TestHttpServer$DummyServletFilter.class
  TestPathFilter.class
  TestHttpServer$MyGroupsProvider.class
  TestHttpServer$1.class
  TestAuthenticationSessionCookie$DummyAuthenticationFilter.class
  TestHttpRequestLog.class
  TestHttpServer$DummyFilterInitializer.class
  TestStaticUserWebFilter.class
  TestHttpServerLogs.class
  TestAuthenticationSessionCookie$Dummy2FilterInitializer.class
  TestHttpServerWithSpengo.class
  TestAuthenticationSessionCookie$DummyFilterInitializer.class
  TestServletFilter$ErrorFilter.class
  TestHttpServer$EchoMapServlet.class
  TestPathFilter$RecordingFilter.class
  TestHttpServer$EchoServlet.class
  TestGlobalFilter$RecordingFilter$Initializer.class
  TestHttpCookieFlag$DummyAuthenticationFilter.class
  TestServiceLifecycle$1.class
  TestCompositeService.class
  TestCompositeService$2$3.class
  TestCompositeService$1.class
  TestCompositeService$2$1.class
  TestServiceInterruptHandling$InterruptCatcher.class
  TestServiceLauncherCreationFailures.class
  TestServiceLauncherInnerMethods.class
  TestServiceConf.class
  TestServiceInterruptHandling$1.class
  TestServiceInterruptHandling.class
  TestServiceLauncher.class
  TestServiceLifecycle$StopInInitService.class
  TestCompositeService$2$2.class
  TestServiceLifecycle$StartInInitService.class
  TestServiceLifecycle.class
  TestCompositeService$CompositeServiceAddingAChild.class
  TestCompositeService$ServiceTestRuntimeException.class
  TestCompositeService$CompositeServiceImpl.class
  TestServiceLifecycle$SelfUnregisteringBreakableStateChangeListener.class
  TestGlobalStateChangeListener.class
  TestServiceLifecycle$AsyncSelfTerminatingService.class
  TestCompositeService$AddSiblingService.class
  TestCompositeService$2.class
  TestServiceLifecycle$NotifyingListener.class
  TestCompositeService$1$1.class
  TestServiceLifecycle$SelfTerminatingService.class
  TestCompositeService$ServiceManager.class
  TestTraceUtils.class
  TestGetInstances$SampleInterface.class
  TestConfigurationSubclass$1.class
  TestConfiguration$Fake_ClassLoader.class
  TestConfiguration$SingleJsonConfiguration.class
  TestConfiguration$Prop.class
  TestConfigurationSubclass.class
  TestReconfiguration$ReconfigurableDummy.class
  TestGetInstances$AnotherClass.class
  TestConfigurationSubclass$SubConf.class
  TestConfiguration$1.class
  TestConfigurationDeprecation$2.class
  TestGetInstances$ChildInterface.class
  TestConfiguration$JsonConfiguration.class
  TestConfigurationFieldsBase.class
  TestReconfiguration$1.class
  TestConfigurationDeprecation$1.class
  TestConfigurationDeprecation.class
  TestReconfiguration$2.class
  TestConfiguration$1ConfigModifyThread.class
  TestGetInstances.class
  TestConfiguration$Yak.class
  TestCommonConfigurationFields.class
  TestConfServlet.class
  TestConfiguration$JsonProperty.class
  TestReconfiguration$AsyncReconfigurableDummy.class
  TestReconfiguration$3.class
  TestDeprecatedKeys.class
  TestConfiguration.class
  TestConfiguration$Dingo.class
  TestReconfiguration.class
  TestGetInstances$SampleClass.class
  TestConfigRedactor.class
  TestGroupsCaching$2.class
  TestShellBasedUnixGroupsMapping$TestNumericGroupResolvable.class
  TestUserGroupInformation$5.class
  TestGroupsCaching.class
  TestNullGroupsMapping.class
  TestUserFromEnv.class
  TestCompositeGroupMapping$GroupMappingProviderBase.class
  TestLdapGroupsMappingWithPosixGroup.class
  TestGroupsCaching$1.class
  TestFixKerberosTicketOrder.class
  TestFixKerberosTicketOrder$3.class
  TestDoAsEffectiveUser$7.class
  TestFixKerberosTicketOrder$2.class
  TestUGIWithSecurityOn.class
  TestGroupFallback.class
  TestLdapGroupsMapping$1.class
  TestLdapGroupsMappingWithOneQuery.class
  TestLdapGroupsMappingBase.class
  TestUserGroupInformation$4.class
  TestShellBasedUnixGroupsMapping$TestGroupNotResolvable.class
  TestUserGroupInformation.class
  TestRaceWhenRelogin$1.class
  TestAuthenticationWithProxyUserFilter$1.class
  TestDoAsEffectiveUser$2.class
  TestUGILoginFromKeytab.class
  TestGroupsCaching$FakeunPrivilegedGroupMapping.class
  TestCrossOriginFilter.class
  TestXFrameOptionsFilter$1.class
  TestXFrameOptionsFilter$4.class
  TestXFrameOptionsFilter$2.class
  TestCrossOriginFilter$FilterConfigTest.class
  TestXFrameOptionsFilter.class
  TestRestCsrfPreventionFilter.class
  TestXFrameOptionsFilter$3.class
  TestReloadingX509TrustManager.class
  TestReloadingX509TrustManager$2.class
  TestSSLFactory.class
  TestReloadingX509TrustManager$1.class
  TestWebDelegationToken$DummyAuthenticationHandler.class
  TestDelegationTokenAuthenticationHandlerWithMocks.class
  TestWebDelegationToken$8.class
  TestWebDelegationToken$2.class
  TestDelegationTokenAuthenticationHandlerWithMocks$MockDelegationTokenAuthenticationHandler$1.class
  TestDelegationTokenManager.class
  TestWebDelegationToken$5.class
  TestWebDelegationToken$7.class
  TestWebDelegationToken$NoDTHandlerDTAFilter.class
  TestWebDelegationToken$KDTAFilter.class
  TestWebDelegationToken$6.class
  TestWebDelegationToken$3.class
  TestWebDelegationToken$KerberosConfiguration.class
  TestWebDelegationToken$IpAddressBasedPseudoDTAFilter.class
  TestWebDelegationToken$PseudoDTAFilter.class
  TestWebDelegationToken$NoDTFilter.class
  TestWebDelegationToken$4.class
  TestWebDelegationToken$PingServlet.class
  TestWebDelegationToken$AFilter.class
  TestWebDelegationToken.class
  TestDelegationTokenAuthenticationHandlerWithMocks$MockDelegationTokenAuthenticationHandler.class
  TestWebDelegationToken$UserServlet.class
  TestWebDelegationToken$UGIServlet.class
  TestWebDelegationToken$DummyDelegationTokenAuthenticationHandler.class
  TestWebDelegationToken$DummyDelegationTokenSecretManager.class
  TestWebDelegationToken$1.class
  TestDelegationTokenAuthenticationHandlerWithMocks$1.class
  TestZKDelegationTokenSecretManager$1.class
  TestDelegationToken$4.class
  TestDelegationToken$TestDelegationTokenSecretManager.class
  TestZKDelegationTokenSecretManager$4.class
  TestZKDelegationTokenSecretManager$3.class
  TestDelegationToken$1tokenIssuerThread.class
  TestZKDelegationTokenSecretManager.class
  TestDelegationToken$TokenSelector.class
  TestZKDelegationTokenSecretManager$2.class
  TestDelegationToken$2.class
  TestDelegationToken$3.class
  TestDelegationToken$1.class
  TestDelegationToken$TestDelegationTokenIdentifier.class
  TestDelegationToken.class
  TestToken.class
  TestDtUtilShell.class
  TestDtFetcher.class
  TestGroupsCaching$FakeGroupMapping.class
  TestHttpCrossOriginFilterInitializer.class
  TestCompositeGroupMapping$1.class
  TestJNIGroupsMapping.class
  TestDoAsEffectiveUser$8.class
  TestGroupsCaching$3.class
  TestNetgroupCache.class
  TestDoAsEffectiveUser$5.class
  TestGroupsCaching$ExceptionalGroupMapping.class
  TestShellBasedUnixGroupsMapping.class
  TestDoAsEffectiveUser$3.class
  TestSecurityUtil.class
  TestDoAsEffectiveUser.class
  TestUserGroupInformation$9.class
  TestUGIWithSecurityOn$1.class
  TestCredShell$MockPasswordReader.class
  TestCredentialProvider.class
  TestCredentialProviderFactory.class
  TestCredShell.class
  TestDoAsEffectiveUser$6.class
  TestUserGroupInformation$DummyLoginConfiguration.class
  TestShellBasedUnixGroupsMapping$1.class
  TestUserGroupInformation$2.class
  TestUserGroupInformation$1.class
  TestCredentials.class
  TestDoAsEffectiveUser$1.class
  TestCompositeGroupMapping$UserProvider.class
  TestUGIWithMiniKdc$1.class
  TestServiceAuthorization$TestProtocol1.class
  TestAccessControlList.class
  TestServiceAuthorization$1.class
  TestProxyUsers.class
  TestProxyUsers$TestDummyImpersonationProvider.class
  TestServiceAuthorization$TestPolicyProvider.class
  TestProxyServers.class
  TestServiceAuthorization.class
  TestUserGroupInformation$7.class
  TestFixKerberosTicketOrder$1.class
  TestShellBasedIdMapping.class
  TestLdapGroupsMapping$2.class
  TestDoAsEffectiveUser$4.class
  TestUserGroupInformation$8.class
  TestUserGroupInformation$3.class
  TestAuthenticationFilter$1.class
  TestCompositeGroupMapping$TestUser.class
  TestKDiagNoKDC.class
  TestShellBasedUnixGroupsMapping$TestDelayedGroupCommand.class
  TestUserGroupInformation$GetTokenThread.class
  TestUGIWithMiniKdc.class
  TestRaceWhenRelogin.class
  TestCompositeGroupMapping.class
  TestLdapGroupsMapping.class
  TestAuthenticationFilter.class
  TestCompositeGroupMapping$ClusterProvider.class
  TestWhitelistBasedResolver.class
  TestShellBasedUnixGroupsMapping$TestGroupResolvable.class
  TestKDiag.class
  TestAuthenticationWithProxyUserFilter.class
  TestUGIWithExternalKdc.class
  TestShellBasedUnixGroupsMapping$TestGroupUserNotExist.class
  TestProxyUserFromEnv.class
  TestUserGroupInformation$6.class
  TestChildReaper.class
  TestClassUtil.class
  TestStringUtils$1.class
  TestStringInterner.class
  TestInstrumentedReadWriteLock$5.class
  TestFindClass$FailInConstructor.class
  TestProtoUtil.class
  TestFindClass$BadToStringClass.class
  TestIdentityHashStore$Key.class
  TestReflectionUtils$2.class
  TestInstrumentedReadWriteLock$2.class
  TestDiskValidatorFactory.class
  TestGSet$IntElement.class
  TestJarFinder.class
  TestBasicDiskValidator.class
  TestIndexedSort$MeasuredSortable.class
  TestShutdownHookManager$2.class
  TestDataChecksum$Harness.class
  TestSysInfoLinux.class
  TestSysInfoLinux$FakeLinuxResourceCalculatorPlugin.class
  TestIdentityHashStore$6.class
  TestIdentityHashStore$1.class
  TestAsyncDiskService$ExampleTask.class
  TestLineReader.class
  TestNativeCodeLoader.class
  TestLightWeightCache.class
  TestInstrumentedReadWriteLock$3.class
  TestDiskChecker.class
  TestInstrumentedReadWriteLock.class
  TestGenericsUtil.class
  TestPureJavaCrc32$PerformanceTest$1.class
  TestLightWeightGSet$TestElement.class
  TestGSet$GSetTestCase.class
  TestPureJavaCrc32$PerformanceTest.class
  TestShell$3.class
  TestAutoCloseableLock.class
  TestInstrumentedLock$1.class
  TestReadWriteDiskValidator.class
  TestInstrumentedLock$3.class
  TestReflectionUtils$LoadedInChild.class
  TestAutoCloseableLock$2.class
  TestShutdownThreadsHelper.class
  TestIdentityHashStore$3.class
  TestLightWeightResizableGSet$TestKey.class
  TestPureJavaCrc32$Table.class
  TestLightWeightCache$IntEntry.class
  TestInstrumentedLock.class
  TestIdentityHashStore$4.class
  TestGSet$IntData.class
  TestNativeLibraryChecker.class
  TestChunkedArrayList.class
  TestVersionUtil.class
  TestReflectionUtils$NoDefaultCtor.class
  TestFindClass.class
  TestInstrumentedReadWriteLock$8.class
  TestInstrumentedLock$5.class
  TestShell$2.class
  TestDataChecksum.class
  TestShutdownHookManager.class
  TestInstrumentedReadWriteLock$4.class
  TestShutdownHookManager$3.class
  TestAsyncDiskService.class
  TestReflectionUtils.class
  TestShell$1.class
  TestDirectBufferPool.class
  TestCacheableIPList.class
  TestIndexedSort$WritableSortable.class
  TestClasspath.class
  TestIdentityHashStore$5.class
  TestFindClass$PrivateClass.class
  TestShutdownThreadsHelper$1.class
  TestReflectionUtils$Parent.class
  TestHash.class
  TestShutdownHookManager$4.class
  TestInstrumentedReadWriteLock$7.class
  TestNativeCrc32.class
  TestWinUtils.class
  TestGenericsUtil$1.class
  TestApplicationClassLoader.class
  TestShell$4.class
  TestDiskChecker$TestFileIoProvider.class
  TestIndexedSort.class
  TestLightWeightCache$IntData.class
  TestStopWatch.class
  TestSysInfoWindows$SysInfoWindowsMock.class
  TestRunJar.class
  TestTime$1.class
  TestStringUtils.class
  TestShell$Command.class
  TestShutdownHookManager$1.class
  TestGSet.class
  TestIdentityHashStore.class
  TestPureJavaCrc32.class
  TestLightWeightCache$LightWeightCacheTestCase.class
  TestAutoCloseableLock$1.class
  TestSignalLogger.class
  TestShell.class
  TestProgress.class
  TestOptions.class
  TestZKUtil.class
  TestReflectionUtils$1.class
  TestInstrumentedLock$2.class
  TestLightWeightResizableGSet.class
  TestSysInfoWindows.class
  TestMachineList.class
  TestHttpExceptionUtils.class
  TestInstrumentedReadWriteLock$9.class
  TestInstrumentedReadWriteLock$1.class
  TestHostsFileReader.class
  TestNodeHealthScriptRunner.class
  TestBloomFilters.class
  TestBloomFilters$1.class
  TestBloomFilters$2.class
  TestBloomFilters$Digits.class
  TestIndexedSort$SampleSortable.class
  TestGenericOptionsParser.class
  TestIdentityHashStore$2.class
  TestTime.class
  TestFindClass$NoEmptyConstructor.class
  TestInstrumentedReadWriteLock$6.class
  TestFileBasedIPList.class
  TestConfTest.class
  TestPureJavaCrc32$PerformanceTest$BenchResult.class
  TestLightWeightGSet.class
  TestFindClass$FailInStaticInit.class
  TestLightWeightResizableGSet$TestElement.class
  TestGenericsUtil$GenericClass.class
  TestInstrumentedLock$4.class
  TestFindClass$PrivateConstructor.class
  TestJMXJsonServlet.class
  TestFileSystemCaching$7.class
  TestFileSystemCaching$DefaultFs.class
  TestTrash.class
  TestContentSummary.class
  TestFsShellReturnCode$1.class
  TestHardLink$1win.class
  TestGetFileBlockLocations.class
  TestStat.class
  TestBlockLocation.class
  TestDelegateToFsCheckPath$UnOverrideDefaultPortFileSystem.class
  TestDFCachingGetSpaceUsed.class
  TestFileContext.class
  TestLocalFileSystemPermission.class
  TestFileSystemCanonicalization.class
  TestDelegationTokenRenewer.class
  TestPath.class
  TestTrash$TestLFS$1.class
  TestFileSystemCaching$6.class
  TestTrash$TestTrashPolicy.class
  TestFileSystemCaching$InitializeForeverFileSystem.class
  TestFsShellReturnCode$RawLocalFileSystemExtn.class
  TestFileSystemStorageStatistics.class
  TestSymlinkLocalFSFileContext.class
  TestTruncatedInputBug.class
  TestAcl.class
  TestFsPermission.class
  TestDU.class
  TestDFVariations.class
  TestGlobExpander.class
  TestAclCommands$StubFileSystem.class
  TestCommandFactory$TestCommand2.class
  TestLs.class
  TestXAttrCommands.class
  TestCommandFactory.class
  TestCommandFactory$TestCommand4.class
  TestLs$TestFile.class
  TestCopyPreserveFlag.class
  TestCount$MockFileSystem.class
  TestMove$1.class
  TestTextCommand.class
  TestCommandFactory$TestCommand1.class
  TestCommandFactory$TestCommand3.class
  TestCount.class
  TestPathData.class
  TestCommandFactory$TestRegistrar.class
  TestPathExceptions.class
  TestMove$InstrumentedRenameCommand.class
  TestTextCommand$1.class
  TestLs$MockFileSystem.class
  TestCount$MockContentSummary.class
  TestMove.class
  TestPrintableString.class
  TestMove$MockFileSystem.class
  TestIname.class
  TestPrint0.class
  TestFind$TestExpression.class
  TestFilterExpression$1.class
  TestAnd.class
  TestFind$FileStatusChecker.class
  TestHelper.class
  TestFilterExpression.class
  TestResult.class
  TestName.class
  TestPrint.class
  TestFind.class
  TestCount$MockQuotaUsage.class
  TestCopy.class
  TestCopy$MockFileSystem.class
  TestAclCommands.class
  TestTrash$1.class
  TestChecksumFileSystem.class
  TestDefaultUri.class
  TestStat$StatOutput.class
  TestFsShellReturnCode.class
  TestTrash$AuditableTrashPolicy$AuditableEmptier.class
  TestHarFileSystem.class
  TestFileStatus.class
  TestHardLink.class
  TestRawLocalFileSystemContract.class
  TestSymlinkLocalFSFileSystem.class
  TestFilterFs$1.class
  TestDelegateToFsCheckPath$OverrideDefaultPortFileSystem.class
  TestFsShellReturnCode$FakeChown.class
  TestDelegationTokenRenewer$1.class
  TestFileUtil.class
  TestCommandFormat.class
  TestFsShellReturnCode$LocalFileSystemExtn.class
  TestTrash$AuditableCheckpoints.class
  TestDelegateToFileSystem.class
  TestHttpFileSystem.class
  TestFsShellCopy.class
  TestAfsCheckPath.class
  TestGetSpaceUsed$DummyDU.class
  TestChRootedFileSystem$MockFileSystem.class
  TestViewFsConfig.class
  TestViewFsURIs.class
  TestChRootedFileSystem.class
  TestViewFsTrash$TestLFS.class
  TestViewFsTrash.class
  TestViewfsFileStatus.class
  TestFcMainOperationsLocalFs.class
  TestViewFileSystemWithAuthorityLocalFileSystem.class
  TestFcCreateMkdirLocalFs.class
  TestViewFileSystemDelegation$FakeFileSystem.class
  TestViewFsConfig$1.class
  TestViewFileSystemDelegationTokenSupport$FakeFileSystem.class
  TestViewFileSystemDelegationTokenSupport.class
  TestViewFsLocalFs.class
  TestFcPermissionsLocalFs.class
  TestViewFsWithAuthorityLocalFs.class
  TestChRootedFs.class
  TestViewFsConfig$1Foo.class
  TestFSMainOperationsLocalFileSystem.class
  TestViewFileSystemDelegation.class
  TestViewFileSystemLocalFileSystem.class
  TestFileContextResolveAfs.class
  TestSFTPFileSystem$1.class
  TestSFTPFileSystem.class
  TestFileSystemTokens.class
  TestAfsCheckPath$DummyFileSystem.class
  TestGetFileBlockLocations$1.class
  TestFileContextDeleteOnExit.class
  TestFcLocalFsUtil.class
  TestQuotaUsage.class
  TestLocalFileSystem.class
  TestTrash$AuditableTrashPolicy.class
  TestDelegateToFsCheckPath$1.class
  TestFilterFileSystem$FilterLocalFileSystem.class
  TestLocalFSContractGetFileStatus.class
  TestLocalFSContractCreate.class
  TestLocalFSContractSetTimes.class
  TestLocalFSContractSeek.class
  TestLocalFSContractLoaded.class
  TestLocalFSContractRename.class
  TestLocalFSContractAppend.class
  TestLocalFSContractOpen.class
  TestLocalFSContractDelete.class
  TestLocalFSContractMkdir.class
  TestFTPContractMkdir.class
  TestFTPContractRename.class
  TestFTPContractCreate.class
  TestFTPContractDelete.class
  TestFTPContractOpen.class
  TestRawlocalContractAppend.class
  TestRawlocalContractMkdir.class
  TestRawlocalContractSetTimes.class
  TestRawlocalContractRename.class
  TestRawlocalContractCreate.class
  TestRawlocalContractOpen.class
  TestRawlocalContractGetFileStatus.class
  TestRawlocalContractDelete.class
  TestRawlocalContractSeek.class
  TestRawLocalContractUnderlyingFileBehavior.class
  TestFileSystemCaching$8.class
  TestDelegationTokenRenewer$3.class
  TestFilterFs$DontCheck.class
  TestFileSystemCaching$3.class
  TestFsOptions.class
  TestTrash$TestLFS.class
  TestFileSystemInitialization.class
  TestFsShellReturnCode$FakeChgrp.class
  TestFsShell.class
  TestFileSystemTokens$1.class
  TestFileSystemCaching$5.class
  TestFileSystemCaching$9.class
  TestFsShellReturnCode$InterruptCommand.class
  TestFsShellList.class
  TestDelegateToFsCheckPath$DummyDelegateToFileSystem.class
  TestLocalDirAllocator.class
  TestDelegateToFsCheckPath.class
  TestFTPFileSystem.class
  TestFileUtil$MyFile.class
  TestFileSystemCanonicalization$DummyFileSystem.class
  TestFsShellTouch.class
  TestListFiles.class
  TestFileSystemCaching$4.class
  TestDelegationTokenRenewer$4.class
  TestFsShellReturnCode$MyFsShell.class
  TestDelegationTokenRenewer$2.class
  TestFcLocalFsPermission.class
  TestLocalFSFileContextMainOperations.class
  TestDelegationTokenRenewer$RenewableFileSystem.class
  TestAvroFSInput.class
  TestFilterFs.class
  TestFileSystemCaching$2.class
  TestLocalFSFileContextCreateMkdir.class
  TestFilterFileSystem$MustNotImplement.class
  TestSymlinkLocalFS.class
  TestFileSystemCaching.class
  TestGetSpaceUsed.class
  TestDFVariations$XXDF.class
  TestHarFileSystemBasics.class
  TestFileSystemCaching$1.class
  TestLocalFileSystem$1.class
  TestGetSpaceUsed$DummyGetSpaceUsed.class
  TestGlobPattern.class
  TestFSMainOperationsLocalFileSystem.class
  TestFilterFileSystem.class
  TestLocalFsFCStatistics.class
  TestHarFileSystem$MustNotImplement.class
  TestCLI.class
  TestCryptoStreams$FakeInputStream.class
  TestCryptoStreams.class
  TestCryptoStreamsNormal.class
  TestCryptoStreamsNormal$1.class
  TestCryptoStreams$FakeOutputStream.class
  TestCryptoStreamsForLocalFS.class
  TestCryptoStreamsWithOpensslAesCtrCryptoCodec.class
  TestCryptoStreams$1.class
  TestCryptoCodec.class
  TestOsSecureRandom.class
  TestOpensslSecureRandom.class
  TestCryptoOutputStreamClosing.class
  TestCryptoStreamsWithJceAesCtrCryptoCodec.class
  TestOpensslCipher.class
  TestKeyProviderDelegationTokenExtension.class
  TestLoadBalancingKMSClientProvider.class
  TestLoadBalancingKMSClientProvider$MyKMSClientProvider.class
  TestValueQueue$FillInfo.class
  TestValueQueue.class
  TestKeyProvider$MyKeyProvider.class
  TestKeyProvider.class
  TestKeyProviderFactory.class
  TestCachingKeyProvider.class
  TestValueQueue$MockFiller.class
  TestKeyProviderCryptoExtension.class
  TestKeyShell.class
  TestKeyProviderCryptoExtension$DummyCachingCryptoExtensionKeyProvider.class
  TestKeyProviderDelegationTokenExtension$MockKeyProvider.class
  TestValueQueue$1.class
  TestKeyProviderCryptoExtension$DummyCryptoExtensionKeyProvider.class
  TestProtoBufRPCCompatibility$NewServerImpl.class
  TestRPC$TestImpl.class
  TestIPCServerResponder$TestServer.class
  TestIPC$TestServer.class
  TestRPCWaitForProxy$RpcThread.class
  TestIPC$10.class
  TestIPC$13.class
  TestAsyncIPC$AsyncCaller.class
  TestSaslRPC$BadTokenSecretManager.class
  TestRPCServerShutdown.class
  TestIPC$TestInvocationHandler.class
  TestRpcServiceProtos$OldProtobufRpcProto$Interface.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$BlockingInterface.class
  TestProtos$AuthMethodResponseProto$1.class
  TestProtos$ExchangeRequestProtoOrBuilder.class
  TestProtos$OptRequestProto$1.class
  TestProtos.class
  TestRpcServiceProtos$OldProtobufRpcProto.class
  TestProtos$AddRequestProto$Builder.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$2.class
  TestProtos$EmptyRequestProto$Builder.class
  TestProtos$AddRequestProtoOrBuilder.class
  TestRpcServiceProtos$CustomProto$1.class
  TestRpcServiceProtos.class
  TestProtos$SleepRequestProto$Builder.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$Interface.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$BlockingInterface.class
  TestRpcServiceProtos$NewerProtobufRpcProto$2.class
  TestProtos$AddResponseProtoOrBuilder.class
  TestProtos$ExchangeResponseProto$Builder.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$Stub.class
  TestRpcServiceProtos$TestProtobufRpc2Proto.class
  TestRpcServiceProtos$NewProtobufRpcProto$Interface.class
  TestProtos$AddResponseProto$1.class
  TestProtos$EmptyResponseProto.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$2.class
  TestProtos$SlowPingRequestProto.class
  TestProtos$EmptyResponseProtoOrBuilder.class
  TestRpcServiceProtos$NewProtobufRpcProto$2.class
  TestProtos$ExchangeResponseProtoOrBuilder.class
  TestProtos$EchoResponseProto$Builder.class
  TestRpcServiceProtos$NewProtobufRpcProto$Stub.class
  TestProtos$UserResponseProtoOrBuilder.class
  TestProtos$EchoResponseProto$1.class
  TestProtos$EmptyResponseProto$Builder.class
  TestProtos$OptResponseProto.class
  TestProtos$AddResponseProto$Builder.class
  TestProtos$AuthMethodResponseProto.class
  TestProtos$AddRequestProto2.class
  TestRpcServiceProtos$CustomProto$2.class
  TestRpcServiceProtos$CustomProto$BlockingInterface.class
  TestProtos$SlowPingRequestProto$Builder.class
  TestProtos$OptRequestProtoOrBuilder.class
  TestProtos$ExchangeResponseProto.class
  TestRpcServiceProtos$NewerProtobufRpcProto$BlockingInterface.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$1.class
  TestRpcServiceProtos$TestProtobufRpcProto$Interface.class
  TestRpcServiceProtos$TestProtobufRpcProto.class
  TestRpcServiceProtos$NewerProtobufRpcProto$Interface.class
  TestProtos$EmptyRequestProto.class
  TestProtos$EchoResponseProto.class
  TestProtos$SleepResponseProto.class
  TestProtos$SleepResponseProto$1.class
  TestProtos$EchoRequestProto$1.class
  TestProtos$EchoRequestProto2OrBuilder.class
  TestProtos$SleepRequestProto2.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$BlockingStub.class
  TestProtos$UserResponseProto$Builder.class
  TestRpcServiceProtos$OldProtobufRpcProto$1.class
  TestRpcServiceProtos$NewerProtobufRpcProto$Stub.class
  TestProtos$SleepResponseProto2$1.class
  TestProtos$EchoRequestProto2$1.class
  TestProtos$EchoResponseProto2.class
  TestProtos$ExchangeResponseProto$1.class
  TestRpcServiceProtos$OldProtobufRpcProto$BlockingStub.class
  TestProtos$AuthMethodResponseProto$Builder.class
  TestProtos$SleepResponseProto2$Builder.class
  TestRpcServiceProtos$NewerProtobufRpcProto$BlockingStub.class
  TestProtos$AddRequestProto2$Builder.class
  TestProtos$EchoRequestProto$Builder.class
  TestRpcServiceProtos$CustomProto$BlockingStub.class
  TestProtos$AddRequestProto$1.class
  TestProtos$AddRequestProto2OrBuilder.class
  TestRpcServiceProtos$NewProtobufRpcProto.class
  TestProtos$AddRequestProto.class
  TestProtos$EchoRequestProto.class
  TestProtos$ExchangeRequestProto$1.class
  TestRpcServiceProtos$NewerProtobufRpcProto$1.class
  TestProtos$SleepRequestProto2$Builder.class
  TestRpcServiceProtos$TestProtobufRpcProto$BlockingInterface.class
  TestProtos$AddRequestProto2$1.class
  TestRpcServiceProtos$OldProtobufRpcProto$BlockingInterface.class
  TestProtos$1.class
  TestProtos$EchoRequestProto2.class
  TestProtos$ExchangeRequestProto$Builder.class
  TestRpcServiceProtos$CustomProto$Stub.class
  TestRpcServiceProtos$CustomProto.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$Stub.class
  TestProtos$SleepResponseProto$Builder.class
  TestRpcServiceProtos$TestProtobufRpc2Proto$Interface.class
  TestProtos$UserResponseProto.class
  TestProtos$EchoResponseProto2OrBuilder.class
  TestRpcServiceProtos$CustomProto$Interface.class
  TestProtos$SleepRequestProto2OrBuilder.class
  TestProtos$EmptyRequestProtoOrBuilder.class
  TestProtos$EchoRequestProtoOrBuilder.class
  TestProtos$OptResponseProtoOrBuilder.class
  TestProtos$EmptyResponseProto$1.class
  TestProtos$OptResponseProto$Builder.class
  TestProtos$EchoResponseProto2$1.class
  TestProtos$OptRequestProto.class
  TestRpcServiceProtos$1.class
  TestRpcServiceProtos$NewerProtobufRpcProto.class
  TestProtos$SleepResponseProto2.class
  TestProtos$SleepRequestProto.class
  TestProtos$OptResponseProto$1.class
  TestProtos$SleepResponseProtoOrBuilder.class
  TestRpcServiceProtos$NewProtobufRpcProto$BlockingInterface.class
  TestRpcServiceProtos$NewProtobufRpcProto$BlockingStub.class
  TestProtos$EchoResponseProtoOrBuilder.class
  TestProtos$SleepRequestProto2$1.class
  TestProtos$SlowPingRequestProto$1.class
  TestRpcServiceProtos$TestProtobufRpcProto$2.class
  TestRpcServiceProtos$OldProtobufRpcProto$Stub.class
  TestProtos$SleepResponseProto2OrBuilder.class
  TestProtos$AuthMethodResponseProtoOrBuilder.class
  TestRpcServiceProtos$OldProtobufRpcProto$2.class
  TestRpcServiceProtos$NewProtobufRpcProto$1.class
  TestRpcServiceProtos$TestProtobufRpcProto$BlockingStub.class
  TestProtos$AddResponseProto.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$1.class
  TestProtos$SleepRequestProtoOrBuilder.class
  TestProtos$EchoRequestProto2$Builder.class
  TestProtos$SleepRequestProto$1.class
  TestProtos$OptRequestProto$Builder.class
  TestProtos$SlowPingRequestProtoOrBuilder.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto.class
  TestProtos$EchoResponseProto2$Builder.class
  TestProtos$UserResponseProto$1.class
  TestRpcServiceProtos$TestProtobufRpcProto$1.class
  TestProtos$EmptyRequestProto$1.class
  TestProtos$ExchangeRequestProto.class
  TestRpcServiceProtos$TestProtobufRpcProto$Stub.class
  TestRpcServiceProtos$TestProtobufRpcHandoffProto$BlockingStub.class
  TestServer$1.class
  TestProtoBufRPCCompatibility$OldRpcService.class
  TestRpcServerHandoff$ClientCallable.class
  TestDecayRpcScheduler.class
  TestReuseRpcConnections.class
  TestRetryCache$TestServer.class
  TestProtoBufRPCCompatibility$NewerServerImpl.class
  TestSaslRPC$AuthSaslPropertiesResolver.class
  TestRPCCompatibility$TestProtocol4.class
  TestRPCWaitForProxy$1.class
  TestRPC$2.class
  TestServer$TestException3.class
  TestServer.class
  TestRPC$5.class
  TestIPC$7.class
  TestIPC$DummyProtocol.class
  TestIPC$4.class
  TestRPC$Transactions.class
  TestIPCServerResponder$3.class
  TestFairCallQueue.class
  TestIPCServerResponder$Caller.class
  TestProtoBufRpc$PBServer2Impl.class
  TestServer$TestException1.class
  TestRpcBase$TestTokenSelector.class
  TestIPC$1.class
  TestIPC$14.class
  TestRPC$1.class
  TestRpcBase$TestRpcService.class
  TestIPC$15.class
  TestCallQueueManager$FakeCall.class
  TestSaslRPC$3.class
  TestIPC$11.class
  TestRPC$8.class
  TestRPCCallBenchmark.class
  TestIPC$12.class
  TestSaslRPC$UseToken.class
  TestIPC$9.class
  TestRpcServerHandoff$1.class
  TestProtoBufRPCCompatibility.class
  TestAsyncIPC$1.class
  TestRPC$11.class
  TestRPC$TestPolicyProvider.class
  TestFairCallQueue$Taker.class
  TestRPCCompatibility$TestProtocol3.class
  TestProtoBufRpcServerHandoff$TestProtoBufRpcServerHandoffProtocol.class
  TestRetryCache$1.class
  TestRPC$FakeRequestClass.class
  TestIPC$5.class
  TestRPCCompatibility$TestProtocol0.class
  TestSaslRPC$4.class
  TestRPC$4.class
  TestIdentityProviders$FakeSchedulable.class
  TestProtoBufRpcServerHandoff$ClientInvocationCallable.class
  TestProtoBufRpcServerHandoff$TestProtoBufRpcServerHandoffServer.class
  TestSaslRPC$CustomSecurityInfo.class
  TestIPC$TestServerQueue.class
  TestIPC$8.class
  TestProtoBufRpc$TestRpcService2.class
  TestCallQueueManager$Taker.class
  TestSocketFactory$DummySocketFactory.class
  TestIPCServerResponder$2.class
  TestRPC$StoppedProtocol.class
  TestIPC$6.class
  TestServer$TestException2.class
  TestRpcServerHandoff$ServerForHandoffTest.class
  TestMultipleProtocolServer.class
  TestRPC.class
  TestMiniRPCBenchmark.class
  TestRPC$3.class
  TestCallQueueManager$ExceptionFakeCall.class
  TestCallQueueManager$Putter.class
  TestIPC$3.class
  TestSaslRPC$CustomSecurityInfo$2.class
  TestAsyncIPC$5.class
  TestFairCallQueue$1.class
  TestCallQueueManager$ExceptionFakeScheduler.class
  TestProtoBufRpcServerHandoff$1.class
  TestRpcBase.class
  TestAsyncIPC$3.class
  TestSaslRPC.class
  TestResponseBuffer.class
  TestIPC$IOEOnReadWritable.class
  TestAsyncIPC$2.class
  TestIPC$2.class
  TestSaslRPC$TestPlainCallbacks$Client.class
  TestSaslRPC$1.class
  TestRPC$10.class
  TestProtoBufRPCCompatibility$NewRpcService.class
  TestRPCCompatibility.class
  TestRPCCompatibility$TestImpl2.class
  TestIPC$CallInfo.class
  TestSaslRPC$TestPlainCallbacks$Server.class
  TestSaslRPC$TestPlainCallbacks.class
  TestRetryCacheMetrics.class
  TestIdentityProviders.class
  TestCallQueueManager.class
  TestRPC$StoppedInvocationHandler.class
  TestRPC$9.class
  TestRPCServerShutdown$1.class
  TestRetryCache.class
  TestRPCCompatibility$TestProtocol1.class
  TestSaslRPC$CustomSecurityInfo$1.class
  TestIPC$IOEOnWriteWritable.class
  TestRpcBase$TestTokenIdentifier.class
  TestRpcBase$TestTokenSecretManager.class
  TestProtoBufRPCCompatibility$OldServerImpl.class
  TestIPCServerResponder.class
  TestSaslRPC$1$1.class
  TestRpcBase$PBServerImpl.class
  TestRpcWritable.class
  TestRPC$TestProtocol.class
  TestAsyncIPC.class
  TestIPC$SerialCaller.class
  TestProtoBufRPCCompatibility$NewerRpcService.class
  TestRPC$TestReaderException.class
  TestRPC$7.class
  TestRPCCompatibility$TestProtocol2.class
  TestRPCCompatibility$TestImpl1.class
  TestRPC$StoppedRpcEngine.class
  TestIPC$NetworkTraces.class
  TestRPCCompatibility$TestImpl0.class
  TestProtoBufRpc.class
  TestAsyncIPC$AsyncLimitlCaller.class
  TestRPC$6.class
  TestSaslRPC$2.class
  TestFairCallQueue$Putter.class
  TestIPC.class
  TestProtoBufRpcServerHandoff.class
  TestSocketFactory$ServerRunnable.class
  TestRpcServerHandoff.class
  TestSocketFactory$1.class
  TestIPCServerResponder$1.class
  TestRPC$SlowRPC.class
  TestWeightedRoundRobinMultiplexer.class
  TestProtoBufRpcServerHandoff$TestProtoBufRpcServerHandoffServer$1.class
  TestIPC$RTEOnWriteWritable.class
  TestIPC$TestInvalidTokenHandler.class
  TestIPC$RTEOnReadWritable.class
  TestRPCWaitForProxy.class
  TestSocketFactory.class
  TestAsyncIPC$4.class
  TestLog4Json.class
  TestLogLevel.class
  TestLog4Json$TestLoggerRepository.class
  TestLogLevel$1.class
  TestLog4Json$TestLogger.class
  TestLog4Json$1.class
  TestClusterTopology.class
  TestTableMapping.class
  TestClusterTopology$NodeElement.class
  TestSwitchMapping$StandaloneSwitchMapping.class
  TestNetworkTopologyWithNodeGroup.class
  TestScriptBasedMapping.class
  TestNetUtils.class
  TestScriptBasedMappingWithDependency.class
  TestStaticMapping.class
  TestSwitchMapping.class
  TestDomainSocket$ReadStrategy.class
  TestDomainSocket$DirectByteBufferReadStrategy.class
  TestDomainSocket$WriteStrategy.class
  TestDomainSocket$2.class
  TestDomainSocketWatcher$2.class
  TestDomainSocket$9.class
  TestDomainSocket$OutputStreamWriteStrategy.class
  TestDomainSocket$ArrayBackedByteBufferReadStrategy.class
  TestDomainSocket$InputStreamReadStrategy.class
  TestDomainSocket$7.class
  TestDomainSocket$3.class
  TestDomainSocketWatcher$3.class
  TestDomainSocketWatcher$4.class
  TestDomainSocket$5.class
  TestDomainSocketWatcher$5$1.class
  TestDomainSocket$PassedFile.class
  TestDomainSocket$6.class
  TestDomainSocketWatcher$3$1.class
  TestDomainSocket.class
  TestDomainSocketWatcher$1.class
  TestDomainSocketWatcher$5.class
  TestDomainSocket$1.class
  TestDomainSocket$8.class
  TestDomainSocketWatcher.class
  TestDomainSocket$4.class
  TestDomainSocketWatcher$6.class
  TestDomainSocketWatcher$7.class
  TestDomainSocket$Success.class
  TestSocketIOWithTimeout$1.class
  TestDNS.class
  TestSocketIOWithTimeout.class
  TestSwitchMapping$1.class
  TestHAAdmin.class
  TestHealthMonitor.class
  TestSshFenceByTcpPort.class
  TestHAAdmin$1.class
  TestActiveStandbyElector.class
  TestZKFailoverControllerStress.class
  TestShellCommandFencer.class
  TestActiveStandbyElector$2.class
  TestFailoverController.class
  TestZKFailoverControllerStress$RandomlyThrow.class
  TestActiveStandbyElectorRealZK.class
  TestHealthMonitorWithDedicatedHealthAddress.class
  TestHealthMonitor$1.class
  TestZKFailoverController$1.class
  TestZKFailoverController.class
  TestActiveStandbyElector$ActiveStandbyElectorTester.class
  TestHealthMonitor$2.class
  TestNodeFencer.class
  TestZKFailoverController$3.class
  TestActiveStandbyElector$1.class
  TestNodeFencer$AlwaysSucceedFencer.class
  TestZKFailoverController$2.class
  TestNodeFencer$AlwaysFailFencer.class
})
public class AllTests { /* empty */}
